name: "CD pipeline"

on:
    workflow_run:
        workflows: ["sample ci workflow"]
        types:
            - completed
    
    workflow_dispatch:
        

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
      
        steps:

            - name: "set up node"
              uses: actions/setup-node@v2
              with:
                node-version: '21'

            - name: "Setup vercel CLI"
              run: npm install -g vercel

            - name: "download build files"
              uses: actions/download-artifact@v2
              with:
                name: build
                workflow: sample ci workflow
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: "deploy to vercel"
              run: vercel --prod --token=${{ secrets.Versal_Token }} --confirm --name=cicdproject 
            
              